/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.IModel;
import model.Kategoria;
import model.Penzmozgas;

/**
 *
 * @author ferenc
 */
public class UjPenzmozgas extends javax.swing.JDialog {

    private IModel model;
    private List<Kategoria> kategoriak;
    private Penzmozgas penzmozgas;
    private boolean szerkesztes;
    private boolean megse;

    public UjPenzmozgas(java.awt.Frame parent, boolean modal, IModel model, Penzmozgas penzmozgas, boolean megse, boolean szerkesztes) {
        super(parent, modal);
        this.model = model;
        this.penzmozgas = penzmozgas;
        this.megse = megse;
        this.szerkesztes = szerkesztes;
        initComponents();

        setLocationRelativeTo(parent);
        if (szerkesztes == false) {
            setTitle("Új pénzmozgás hozzáadása");
        } else {
            setTitle("Pénzmozgás szerkesztése");
        }

        try {
            kategoriak = model.getAllKategoria();
            cbox.setModel(new DefaultComboBoxModel<Kategoria>(kategoriak.toArray(new Kategoria[kategoriak.size()])));

            if (szerkesztes) {
                int katID = penzmozgas.getKategoria();
                Kategoria beir = new Kategoria();
                for (int i = 0; i < kategoriak.size(); i++) {
                    if (katID == kategoriak.get(i).getId()) {
                        beir = kategoriak.get(i);
                    }
                }

                cbox.setSelectedItem(beir);
                tfOsszeg.setText(Integer.toString(penzmozgas.getOsszeg()));
                tfMegjegyzes.setText(penzmozgas.getMegjegyzes());
                tfDatum.setText(penzmozgas.getDatum().toString());
                        
                
                
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(parent, ex, "Adatbázis hiba", JOptionPane.ERROR_MESSAGE);
        }

    }

    public boolean isMegse() {
        return megse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfOsszeg = new javax.swing.JTextField();
        tfDatum = new javax.swing.JTextField();
        tfMegjegyzes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbOK = new javax.swing.JButton();
        jbMegse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("A kiadás típusa");

        jLabel2.setText("Összeg");

        jLabel3.setText("Dátum");

        jLabel4.setText("Megjegyzés");

        jbOK.setBackground(new java.awt.Color(249, 248, 248));
        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbMegse.setBackground(new java.awt.Color(246, 129, 1));
        jbMegse.setText("Mégse");
        jbMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMegseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbMegse)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMegjegyzes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(tfDatum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfOsszeg, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMegjegyzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMegse)
                    .addComponent(jbOK))
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDatum, tfMegjegyzes, tfOsszeg});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMegseActionPerformed
        this.setVisible(false);
        megse = true;
    }//GEN-LAST:event_jbMegseActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        if (!tfDatum.getText().equals("") || !tfMegjegyzes.getText().equals("")
                || !tfOsszeg.getText().equals("")) {
            megse = false;
            penzmozgas.setDatum((LocalDate.parse(tfDatum.getText())));
            penzmozgas.setOsszeg(Integer.parseInt(tfOsszeg.getText()));
            penzmozgas.setMegjegyzes(tfMegjegyzes.getText());

            Kategoria kat = (Kategoria) cbox.getSelectedItem();

            int id = kat.getId();

            penzmozgas.setIdKategoria(id);

            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Be kéne írni minden adatot!", "Irgumburgum.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbOKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbMegse;
    private javax.swing.JButton jbOK;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfMegjegyzes;
    private javax.swing.JTextField tfOsszeg;
    // End of variables declaration//GEN-END:variables

    public boolean isSzerkesztes() {
        return szerkesztes;
    }
}
